export default {
  unreadNotifications: 5,
  notifications: [
    {
      notify_id: 56,
      notify_by: 7,
      notify_by_username: 'ghalib',
      notify_time: '1480114098767',
      type: 'follow',
      user: 0,
      user_username: '',
      post_id: 0,
      group_id: 0,
      isFollowing: false,
    },
    {
      notify_id: 57,
      notify_by: 7,
      notify_by_username: 'ghalib',
      notify_time: '1480114098767',
      type: 'recommend',
      user: 8,
      user_username: 'coldplay',
      post_id: 0,
      group_id: 0,
      isFollowing: false,
    },
    {
      notify_id: 58,
      notify_by: 7,
      notify_by_username: 'ghalib',
      notify_time: '1480114098767',
      type: 'like',
      user: 0,
      user_username: '',
      post_id: 27,
      group_id: 0,
      isFollowing: false,
    },
    {
      notify_id: 59,
      notify_by: 7,
      notify_by_username: 'ghalib',
      notify_time: '1480114098767',
      type: 'invite',
      user: 0,
      user_username: '',
      post_id: 0,
      group_id: 11,
      isFollowing: false,
    },
  ],
}
